"""
Django settings for test_task project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6w#kkpx82h%-ri$o(3*+p0e^0o-4v6ik)m!(4nzs!f=u$x**_$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

REDIRECT_URI = 'http://ce71-95-37-129-249.ngrok.io'
CLIENT_ID = 'da653128-4343-4220-8517-a448592c8a71'
CLIENT_SECRET = '43nRENr06eCeRkoLWohWASD4YoW1Ks6PpN8N4ECPKeAg8oabpY2pMPVgS6x7dAx0'
CODE = 'def502009227829c120ad0242d1e405118e17d442c3d26356e732c17494af7d95f4ee827151dfe1babfd6ffee4f4b5c4af04a0397f0abab665f14737fb431492f593a1c75e3241f345018991f5e1a99dd68761c29be865528ffc16b5a16b71292eb6bacc6e0c4a2bd5e5a6ed5bd06c84994fc11e687abda097bff148b1f24dc23a5b50d80ec7b4efb309c331bdd09f05e61f5d88565dd0818b1d47b0fd5e5144a1fa6278b24f79d6154b4141e5abe7eb82f94af98ccc56fc5e2d5c6b41109a3b621e063ac579a3f3646e3e1de7d343de0043631a023e9c0e7ba49b1238c157669cff829def23b096c3939ef144698fa95c310ca33e24c0a5f5dc68d28043f03d2e73c67fe491ca8239c5e471b7dce2b7d0bd0b9985a8c7babc5cd713e1f38f442ee839d1378adff3b1ddb3e9c04a681926e4dbc39ad1bb9debb29f98f0a8c1a9a267fd39a81aa6fc3e545ed5639e0ad5762867fc89236da42262a04ada786271347c1104ef47dafec76e8ee7a9e6a5e144e964bc3574f8295a7817aedff73a8d04eb2dca40a5ff0280a500b0a1e786e2c880b6ef9bede60d623faf8264b6f94623ddfe142bdf7020223d22d4f3ea50b32b17cfea39e5bb3c49427b23a67266a04f30a29a3f2ece9cc1c5032b'
MY_URI = 'https://jigsaw11211.amocrm.ru/'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'backend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'test_task.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'test_task.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
