"""empty message

Revision ID: 66b13fb0aa57
Revises: ca61944f05af
Create Date: 2020-11-30 00:02:27.253217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b13fb0aa57'
down_revision = 'ca61944f05af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'post_id')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'author', ['author_id'], ['id'])
    op.drop_column('post', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    op.add_column('author', sa.Column('post_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
